swagger: '2.0'
info:
  description: API for Car Rental
  version: '1.1.0'
  title: Car Rental Methods API
  
  contact:
   email: test@test.com
  license:
   name: Test 2.0 
   url: "https://www.google.com"
paths:
  /reservation:
   post:
    summary: Reservate a car
    operationId: reservateCar
    description: Reservate a car
    tags:
     - Reservation
    parameters:
      - $ref: './parameters.yaml#/parameters/cars'  
    produces:
      - application/json
    responses:
        '200':
          description: Successful operation
          schema:
           $ref: './model.yaml#/definitions/CollectionReservations'
        '201':
          description: CREATED
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
 
  /customer/{customerId}:
   get:
    summary: Get Customer Reservations
    operationId: getCustomerReservation
    description: Get Cars Informations and his price with surcharges from the customer 
    tags: 
     - Customer
    produces:
      - application/json
    parameters:
      - name: customerId
        in: path
        required: true
        type: integer
        format: int64
        description: customerId
        example: 1
    responses:
        '200':
          description: Successful operation
          schema:
           $ref: './model.yaml#/definitions/ReservationSurchargesDTO'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
basePath: /
schemes:
 - https
 - http
host: virtserver.swaggerhub.com           